spring:
  application:
    name: smart-vision
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: 0
      timeout: 3000ms

aliyun:
  oss:
    endpoint: ${OSS_ENDPOINT}
    public-endpoint: ${OSS_PUBLIC_ENDPOINT}
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucket-name: ${ALIYUN_OSS_BUCKET_NAME}
    role-arn: ${ALIYUN_OSS_ROLE_ARN}
  ocr:
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    endpoint: ${OCR_ENDPOINT}

app:
  security:
    admin-secret: ${APP_ADMIN_SECRET}


