spring:
  application:
    name: smart-vision

aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    public-endpoint: ryansimg.oss-cn-shanghai.aliyuncs.com
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucket-name: ryansimg



